### ISSUE TITLE
0.5.0 release checklist

### ISSUE THREAD

**Issue by AaronErhardt** [Relm4/Relm4#394]
- [x] Merge #391 and publish rc2
- [x] Update "Threads and async" chapter (will be done by me)
- [x] Release Relm4 snippets on Open VSIX
- [x] Finish the release article (https://github.com/Relm4/blog/pull/4)
- [x] Review and merge all remaining [0.5 milestone PRs](https://github.com/Relm4/Relm4/pulls?q=is%3Apr+is%3Aopen+milestone%3A0.5+)
- [x] Merge #383
- [ ] Decide how to move on with docs and the book (change links to stable, moving the 0.4 docs and book somewhere else)
