### ISSUE TITLE
0.6 release checklist

### ISSUE THREAD

**Issue by AaronErhardt** [Relm4/Relm4#460]
Add "tips and tricks" chapter to the book with common mistakes and regularly overlooked features
- [ ] #420: Message recursion
- [ ] #455: `#[wrap(Some)]`
- [ ] #375: Saving window state
- [ ] #325: match and if else in the view macro (also add this to macro reference)
- [ ] Reasons for `RelmContainerExt` error
- [ ] GTK inspektor
- [ ] Reading gtk-rs docs

**Comment by adhadse** [comment]
On version `0.6.0` the libadwaita fails to compile:
```
[0/1] Generating src/cargo-build with a custom command
   Compiling libadwaita v0.4.2
error[E0432]: unresolved import `crate::SpinRow`
 --> /home/adhadse/Documents/bookx-testing/_build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/libadwaita-0.4.2/src/spin_row.rs:3:5
  |
3 | use crate::SpinRow;
  |     ^^^^^^^^^^^^^^ no `SpinRow` in the root

error[E0618]: expected function, found `&F`
  --> /home/adhadse/Documents/bookx-testing/_build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/libadwaita-0.4.2/src/spin_row.rs:34:11
   |
32 |     f: &F,
   |     - `f` has type `&F`
33 | ) -> c_int {
34 |     match f(SpinRow::from_glib_borrow(this).unsafe_cast_ref()) {
   |           ^---------------------------------------------------
   |           |
   |           call expression requires function

Some errors have detailed explanations: E0432, E0618.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `libadwaita` due to 2 previous errors
FAILED: src/bookx-testing 
```

I have installed `libadwaita-devel-1.3.2-1.fc38.x86_64` on Fedora. Is this relevant to `0.6.0` release?

**Comment by AaronErhardt** [comment]
@adhadse libadwaita v0.4.2 was published just 2 hours ago and causes this issue. By the time 0.6.0 was released, everything worked as expected, so this must be a regression in libadwaita-rs.

**Comment by adhadse** [comment]
I thought relm4 0.6 release had fixed libadwaita version 0.4.1 🤔

**Comment by AaronErhardt** [comment]
Well, Relm4 0.6.0 specifically released with the libadwaita requirement of 0.4: [look at our Cargo.toml](https://github.com/Relm4/Relm4/blob/main/relm4/Cargo.toml#L42).

This means, that you can use it with any 0.4.x release of libadwaita, which currently are 0.4.0, 0.4.1 and 0.4.2. Usually, cargo picks the latest, which is the broken 0.4.2 in this case. To fix this, you can temporarily pin 0.4.1 in your Cargo.toml, but is doesn't make sense to fix this in Relm4 unless libadwaita doesn't get an update soon. You can read more about this in the [cargo book](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html).

**Comment by AaronErhardt** [comment]
Btw. a patch for libadwaita is on the way.
